### ISSUE TITLE
Websocket 服务会报错

### ISSUE THREAD

**Issue by huangdijia** [Gemini-D/hyperf-router#1]
https://github.com/Gemini-D/hyperf-router/blob/ccb7ee21859e5a7e01b4e03ce31d662dcdce50b2/src/HttpDispatcher.php#L51

当是 websocket 的时候 $method 的值是 null

**Comment by limingxinleo** [comment]
试试 dev-main 的代码

**Comment by huangdijia** [comment]
https://github.com/Gemini-D/hyperf-router/blob/0a8dbf81d401eac5042b36a6718a9af75bb7a577/src/HttpDispatcher.php#L86

这里应该是不是要这样改一下：

```php
        if (is_string($handler)) {
            if (strpos($handler, '@') !== false) {
                return explode('@', $handler);
            }
            if (strpos($handler, '::') !== false) {
                return explode('::', $handler);
            }
            return [$handler, null];
        }
```

**Comment by huangdijia** [comment]
测试过了，可以通过

**Comment by limingxinleo** [comment]
发新版本了
